name: Internal links

on:
  pull_request:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check internal links and images
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          fail: true
          args: >-
            --no-progress
            --offline
            --exclude-path .git
            --exclude-path .tmp
            './**/*.md'
